In [2]:
import pandas as pd
import os

In [3]:
UploadCustomReportActionFileName = "C:/Users/ymann/Desktop/python_gui/Report - Custom - May 17, 2022 - 20_28 (2).xlsx"
clientCustomReportDataframe = pd.read_excel (UploadCustomReportActionFileName)

In [4]:
UploadAccessActualActionFileName = "C:/Users/ymann/Desktop/python_gui/ClientAccess_Actual (2).xlsx"
clientActualAccessDataframe= pd.read_excel (UploadAccessActualActionFileName)

In [6]:
UploadClappedActionFileName = "C:/Users/ymann/Desktop\python_gui/ClientCappedHours_Actual (1).xlsx"
clappedHoursDataframe = pd.read_excel (UploadClappedActionFileName)

In [56]:
clientActualAccessDataframe

,Id,Employee,Position,Grouper,Guppy,Sheepshead,Catfish,Zander
0,6633105,Alexander Demergis,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
1,6600944,Ali Irfan,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
2,5851841,Alonzo Williams,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
3,6296070,Anand Patel,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
4,4646339,Annmarie Silva,FMS Group Y L2,Y,Y,Y,Y,N
5,6662076,Ashok Velat,FMS SOC Group X (US Only),N,N,N,N,Y
6,6255148,Atiba Lashley,FMS SOC Group X (US Only),N,N,N,N,Y
7,6825586,Ayodeji Odukogbe,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
8,6339055,Benedita Pinto,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
9,6296069,Bilal Haciogullari,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
10,6886138,Brandon Richardson,FMS SOC Group X (US Only),N,N,N,N,Y
11,6643860,Chris Bonsu,FMS SOC Group X (US Only),N,N,N,N,Y
12,5304095,Daria Moaadel,FMS Group X L2,N,N,N,N,Y
13,6411950,Eve Ekkardt,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
14,6600942,Griffin Fried,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
15,6729801,Irfan Jeelani,FMS SOC Group X (US Only),N,N,N,N,Y
16,6364591,Isaiah Harris-Winn,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
17,4544637,Jack Spera,FMS Group X L2,N,N,N,N,Y
18,6812524,Jeenho Hahm,FMS SOC Group X (US Only),N,N,N,N,Y
19,6460742,Jeremy Ansher,FMS SOC Group X (US Only),N,N,N,N,Y
20,4831863,Jesse Mainor,FMS Group Y L2,Y,Y,Y,Y,N
21,6059866,Jineva Byrne,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
22,4767242,Juhi Agarwal,FMS Group Y L2,Y,Y,Y,Y,N
23,6296067,Kabah Arku,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
24,6886139,Kabeer Mehdi,FMS SOC Group X (US Only),N,N,N,N,Y
25,6021680,Kenley Anglade,FMS SOC Group X (US Only),N,N,N,N,Y
26,6411976,Kenny Mei,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
27,6954779,Lane Schoof,FMS SOC Group X (US Only),N,N,N,N,Y
28,6746562,Lashon Enezuagu,FMS SOC Group X (US Only),N,N,N,N,Y
29,3949101,Logan Shaulis,Shift Lead,N,N,N,N,Y
30,6825587,Marvelous Kings,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
31,6954781,Merve Ece,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
32,5293390,Michael Francis,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
33,4450037,Micheal Maher,FMS Group X L2,N,N,N,N,Y
34,6315165,Nour Lamkhenter,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
35,6296071,Ozdal Etlik,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
36,6758500,Precious Adagbon,FMS SOC Group X (US Only),N,N,N,N,Y
37,5972947,Ronald Myers,FMS SOC Group X (US Only),N,N,N,N,Y
38,6966968,Sam Anderson,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
39,5176466,Samuel Smith,FMS Group X L2,N,N,N,N,Y
40,6332382,Sena Ozeren,FMS SOC Group Y (US Only),Y,Y,Y,Y,N
41,4521985,Solomon Kassahun,FMS SOC Group X (US Only),N,N,N,N,Y
42,6779701,Tyler Medina,FMS SOC Group X (US Only),N,N,N,N,Y
43,3330389,Viswanatha Vaddi,FMS Group Y L2,Y,Y,Y,Y,N
44,6255144,Yusuf Ahmad,FMS SOC Group X (US Only),N,N,N,N,Y
45,6519594,Zavier Stambaugh,FMS SOC Group Y (US Only),Y,Y,Y,Y,N

In [55]:
outputFrameColumns=["Employee ID","Employee Name","Employee Level","Total Working Hours"]
for client in clappedHoursDataframe['Client Name']:
    outputFrameColumns.append(client)
outputFrameColumns.append('Total Hours Charged by Employee')
outputFrameColumns.append('Hours Worked - Hours Charged')
outputFrameColumns.append('Ratio')

gk=clientCustomReportDataframe.groupby('employee')

outputFrameData=[]

for idx in clientCustomReportDataframe.index:
    totalHrs=gk.get_group(clientCustomReportDataframe['employee'][idx])['total_time'].agg('sum')
    outputSheetRow=[clientCustomReportDataframe['id'][idx],
        clientCustomReportDataframe['employee'][idx],
        clientCustomReportDataframe['Level'][idx],
        totalHrs
    ]
    for client in clappedHoursDataframe['Client Name']:
        rw=clientActualAccessDataframe[clientActualAccessDataframe['Id']==clientCustomReportDataframe['id'][idx]][client]
        string=rw.to_string(index=False)
        if string=='N':
            outputSheetRow.append(0)
        else:
            outputSheetRow.append("")
    outputSheetRow.append(0)
    outputSheetRow.append(0)
    outputSheetRow.append(0)

    outputFrameData.append(outputSheetRow)

outputDataFrame=pd.DataFrame(outputFrameData,columns=outputFrameColumns)
outputDataFrame=outputDataFrame.drop_duplicates(subset=['Employee ID'],keep='first')

dict={}
for client in clappedHoursDataframe['Client Name']:
        dict[client]=0

for idx in outputDataFrame.index:
    for client in clappedHoursDataframe['Client Name']:
        if outputDataFrame[client][idx]!=0:
            dict[client]+=outputDataFrame['Total Working Hours'][idx]

for idx in outputDataFrame.index:
    for client in clappedHoursDataframe['Client Name']:
        if outputDataFrame[client][idx]!=0:
            clappedHours=clappedHoursDataframe[clappedHoursDataframe['Client Name']==client]['Capped Hours Per Week']
            clappedHours=(float)(clappedHours.to_string(index=False))
            calc=(outputDataFrame['Total Working Hours'][idx]/dict[client])*(clappedHours)
            outputDataFrame.at[idx,client]=calc

0.7890583903208838
Grouper 0
0.7890583903208838
Guppy 0
0.7890583903208838
Sheepshead 0
0.7890583903208838
Catfish 0
4.5183231538034425
Zander 1
4.5183231538034425
Zander 2
0.7890583903208838
Grouper 3
0.7890583903208838
Guppy 3
0.7890583903208838
Sheepshead 3
0.7890583903208838
Catfish 3
0.7890583903208838
Grouper 4
0.7890583903208838
Guppy 4
0.7890583903208838
Sheepshead 4
0.7890583903208838
Catfish 4
0.7890583903208838
Grouper 5
0.7890583903208838
Guppy 5
0.7890583903208838
Sheepshead 5
0.7890583903208838
Catfish 5
0.7890583903208838
Grouper 6
0.7890583903208838
Guppy 6
0.7890583903208838
Sheepshead 6
0.7890583903208838
Catfish 6
4.5183231538034425
Zander 7
0.7890583903208838
Grouper 8
0.7890583903208838
Guppy 8
0.7890583903208838
Sheepshead 8
0.7890583903208838
Catfish 8
4.5183231538034425
Zander 8
4.5183231538034425
Zander 9
1.5061077179344808
Zander 10
0.7995791688584954
Grouper 17
0.7995791688584954
Guppy 17
0.7995791688584954
Sheepshead 17
0.7995791688584954
Catfish 17
4.578567462520821
Zander 17
0.7995791688584954
Grouper 18
0.7995791688584954
Guppy 18
0.7995791688584954
Sheepshead 18
0.7995791688584954
Catfish 18
0.7995791688584954
Grouper 19
0.7995791688584954
Guppy 19
0.7995791688584954
Sheepshead 19
0.7995791688584954
Catfish 19
0.7995791688584954
Grouper 20
0.7995791688584954
Guppy 20
0.7995791688584954
Sheepshead 20
0.7995791688584954
Catfish 20
4.578567462520821
Zander 21
0.7995791688584954
Grouper 22
0.7995791688584954
Guppy 22
0.7995791688584954
Sheepshead 22
0.7995791688584954
Catfish 22
4.578567462520821
Zander 22
0.7995791688584954
Grouper 23
0.7995791688584954
Guppy 23
0.7995791688584954
Sheepshead 23
0.7995791688584954
Catfish 23
4.578567462520821
Zander 24
4.578567462520821
Zander 25
4.578567462520821
Zander 26
4.578567462520821
Zander 27
0.7995791688584954
Grouper 28
0.7995791688584954
Guppy 28
0.7995791688584954
Sheepshead 28
0.7995791688584954
Catfish 28
0.7995791688584954
Grouper 29
0.7995791688584954
Guppy 29
0.7995791688584954
Sheepshead 29
0.7995791688584954
Catfish 29
4.578567462520821
Zander 30
0.7995791688584954
Grouper 31
0.7995791688584954
Guppy 31
0.7995791688584954
Sheepshead 31
0.7995791688584954
Catfish 31
0.7995791688584954
Grouper 32
0.7995791688584954
Guppy 32
0.7995791688584954
Sheepshead 32
0.7995791688584954
Catfish 32
0.7995791688584954
Grouper 33
0.7995791688584954
Guppy 33
0.7995791688584954
Sheepshead 33
0.7995791688584954
Catfish 33
4.578567462520821
Zander 33
4.578567462520821
Zander 34
4.578567462520821
Zander 35
0.5996843766438716
Grouper 36
0.5996843766438716
Guppy 36
0.5996843766438716
Sheepshead 36
0.5996843766438716
Catfish 36
0.7995791688584954
Grouper 37
0.7995791688584954
Guppy 37
0.7995791688584954
Sheepshead 37
0.7995791688584954
Catfish 37
4.578567462520821
Zander 38
3.4339255968906164
Zander 39
0.7995791688584954
Grouper 40
0.7995791688584954
Guppy 40
0.7995791688584954
Sheepshead 40
0.7995791688584954
Catfish 40
4.578567462520821
Zander 40
0.7995791688584954
Grouper 41
0.7995791688584954
Guppy 41
0.7995791688584954
Sheepshead 41
0.7995791688584954
Catfish 41
4.578567462520821
Zander 42
0.7995791688584954
Grouper 43
0.7995791688584954
Guppy 43
0.7995791688584954
Sheepshead 43
0.7995791688584954
Catfish 43
4.578567462520821
Zander 44
0.3997895844292477
Grouper 45
0.3997895844292477
Guppy 45
0.3997895844292477
Sheepshead 45
0.3997895844292477
Catfish 45
4.578567462520821
Zander 46
0.9468700683850605
Grouper 47
0.9468700683850605
Guppy 47
0.9468700683850605
Sheepshead 47
0.9468700683850605
Catfish 47
5.421987784564131
Zander 47
2.2892837312604106
Zander 84
0.3997895844292477
Grouper 89
0.3997895844292477
Guppy 89
0.3997895844292477
Sheepshead 89
0.3997895844292477
Catfish 89
0.3997895844292477
Grouper 101
0.3997895844292477
Guppy 101
0.3997895844292477
Sheepshead 101
0.3997895844292477
Catfish 101
0.5260389268805892
Grouper 135
0.5260389268805892
Guppy 135
0.5260389268805892
Sheepshead 135
0.5260389268805892
Catfish 135
     Employee ID       Employee Name Employee Level  Total Working Hours  \
0        6825586    Ayodeji Odukogbe             A4                 37.5
1        6460742       Jeremy Ansher             A4                 37.5
2        6021680      Kenley Anglade             A4                 37.5
3        6825587     Marvelous Kings             A4                 37.5
4        5293390     Michael Francis             A4                 37.5
5        6519594    Zavier Stambaugh             A4                 37.5
6        5851841     Alonzo Williams             A4                 37.5
7        6886138  Brandon Richardson             A4                 37.5
8        3935464    Kishore Sreerama             A6                 37.5
9        5176466        Samuel Smith           A5 I                 37.5
10       6255144         Yusuf Ahmad             A4                 12.5
17       7012947         Addy Kadura             A4                 38.0
18       6633105  Alexander Demergis             A4                 38.0
19       6600944           Ali Irfan             A4                 38.0
20       6296070         Anand Patel             A4                 38.0
21       6643860         Chris Bonsu             A4                 38.0
22       7000678     Ericka Granison             A4                 38.0
23       6600942       Griffin Fried             A4                 38.0
24       4544637          Jack Spera           A5 I                 38.0
25       6812524         Jeenho Hahm             A4                 38.0
26       6954779         Lane Schoof             A4                 38.0
27       3949101       Logan Shaulis          A5 II                 38.0
28       6954781           Merve Ece             A4                 38.0
29       6315165     Nour Lamkhenter             A4                 38.0
30       6758500    Precious Adagbon             A4                 38.0
31       6966968        Sam Anderson             A4                 38.0
32       6332382         Sena Ozeren             A4                 38.0
33       6063385       Sharise Odems             A4                 38.0
34       6779701        Tyler Medina             A4                 38.0
35       6255148       Atiba Lashley             A4                 38.0
36       6339055      Benedita Pinto             A4                 28.5
37       6364591  Isaiah Harris-Winn             A4                 38.0
38       6886139        Kabeer Mehdi             A4                 38.0
39       4450037       Micheal Maher          A5 II                 28.5
40       3330384          Rahul Shah          A6 II                 38.0
41       3330389    Viswanatha Vaddi           A6 I                 38.0
42       6662076         Ashok Velat             A4                 38.0
43       6296069  Bilal Haciogullari             A4                 38.0
44       6729801       Irfan Jeelani             A4                 38.0
45       6296071         OZDAL ETLIK             A4                 19.0
46       5972947        Ronald Myers             A4                 38.0
47       3515839       Aditi Binnani             A6                 45.0
84       5304095       Daria Moaadel           A5 I                 19.0
89       6296067          Kabah Arku             A4                 19.0
101      6411950         Eve Ekkardt             A4                 19.0
135      6411976           Kenny Mei             A4                 25.0

      Grouper     Guppy Sheepshead   Catfish    Zander  \
0    0.789058  0.789058   0.789058  0.789058         0
1           0         0          0         0  4.518323
2           0         0          0         0  4.518323
3    0.789058  0.789058   0.789058  0.789058         0
4    0.789058  0.789058   0.789058  0.789058         0
5    0.789058  0.789058   0.789058  0.789058         0
6    0.789058  0.789058   0.789058  0.789058         0
7           0         0          0         0  4.518323
8    0.789058  0.789058   0.789058  0.789058  4.518323
9           0         0          0         0  4.518323
10          0         0          0         0  1.506108
17   0.799579  0.799579   0.799579  0.799579  4.578567
18   0.799579  0.799579   0.799579  0.799579         0
19   0.799579  0.799579   0.799579  0.799579         0
20   0.799579  0.799579   0.799579  0.799579         0
21          0         0          0         0  4.578567
22   0.799579  0.799579   0.799579  0.799579  4.578567
23   0.799579  0.799579   0.799579  0.799579         0
24          0         0          0         0  4.578567
25          0         0          0         0  4.578567
26          0         0          0         0  4.578567
27          0         0          0         0  4.578567
28   0.799579  0.799579   0.799579  0.799579         0
29   0.799579  0.799579   0.799579  0.799579         0
30          0         0          0         0  4.578567
31   0.799579  0.799579   0.799579  0.799579         0
32   0.799579  0.799579   0.799579  0.799579         0
33   0.799579  0.799579   0.799579  0.799579  4.578567
34          0         0          0         0  4.578567
35          0         0          0         0  4.578567
36   0.599684  0.599684   0.599684  0.599684         0
37   0.799579  0.799579   0.799579  0.799579         0
38          0         0          0         0  4.578567
39          0         0          0         0  3.433926
40   0.799579  0.799579   0.799579  0.799579  4.578567
41   0.799579  0.799579   0.799579  0.799579         0
42          0         0          0         0  4.578567
43   0.799579  0.799579   0.799579  0.799579         0
44          0         0          0         0  4.578567
45    0.39979   0.39979    0.39979   0.39979         0
46          0         0          0         0  4.578567
47    0.94687   0.94687    0.94687   0.94687  5.421988
84          0         0          0         0  2.289284
89    0.39979   0.39979    0.39979   0.39979         0
101   0.39979   0.39979    0.39979   0.39979         0
135  0.526039  0.526039   0.526039  0.526039         0

     Total Hours Charged by Employee  Hours Worked - Hours Charged  Ratio
0                                  0                             0      0
1                                  0                             0      0
2                                  0                             0      0
3                                  0                             0      0
4                                  0                             0      0
5                                  0                             0      0
6                                  0                             0      0
7                                  0                             0      0
8                                  0                             0      0
9                                  0                             0      0
10                                 0                             0      0
17                                 0                             0      0
18                                 0                             0      0
19                                 0                             0      0
20                                 0                             0      0
21                                 0                             0      0
22                                 0                             0      0
23                                 0                             0      0
24                                 0                             0      0
25                                 0                             0      0
26                                 0                             0      0
27                                 0                             0      0
28                                 0                             0      0
29                                 0                             0      0
30                                 0                             0      0
31                                 0                             0      0
32                                 0                             0      0
33                                 0                             0      0
34                                 0                             0      0
35                                 0                             0      0
36                                 0                             0      0
37                                 0                             0      0
38                                 0                             0      0
39                                 0                             0      0
40                                 0                             0      0
41                                 0                             0      0
42                                 0                             0      0
43                                 0                             0      0
44                                 0                             0      0
45                                 0                             0      0
46                                 0                             0      0
47                                 0                             0      0
84                                 0                             0      0
89                                 0                             0      0
101                                0                             0      0
135                                0                             0      0